export const BEERS = [
  "Albae cerevisiae",
  "Altbier",
  "American amber ale",
  "American barleywine",
  "American blonde ale",
  "American brown ale",
  "American IPA",
  "American porter",
  "American stout",
  "American strong ale",
  "American wheat",
  "Angielski porter",
  "Angielskie barley wine",
  "Angielskie pale ale",
  "Australian sparkling ale",
  "Bawarskie ciemne (dunkles)",
  "Bawarskie jasne (helles)",
  "Belgian blond ale",
  "Belgian dark strong ale (quadrupel)",
  "Belgian dubbel",
  "Belgian golden strong ale",
  "Belgian pale ale",
  "Belgian triple",
  "Belgijska IPA",
  "Berliner weisse",
  "Bière de garde",
  "Bitter",
  "British golden ale",
  "British strong ale",
  "Brown IPA",
  "Burton ale",
  "California common",
  "Ciemne lekkie (tmavé výčepní)",
  "Ciemne mocne (tmavý speciál)",
  "Ciemne pełne (tmavý ležák)",
  "Coffee pale ale",
  "Cream ale",
  "Czeskie półciemne (polotmavé)",
  "Dortmunder Export",
  "Double IPA",
  "Dunkles weissbier",
  "Festbier",
  "Festbock",
  "Gose",
  "Grodziskie",
  "Hvidtøl",
  "Imperialny stout",
  "India pale ale",
  "Irish dry stout",
  "Irish red ale",
  "Jasne lekkie (světlé výčepní)",
  "Jasne mocne (světlý speciál)",
  "Jasne pełne (světlý ležák)",
  "Jasny koźlak (helles bock)",
  "Jasny lager",
  "Kellerbier (zwickelbier)",
  "Kentucky common",
  "Kolońskie (kölsch)",
  "Koźlak (bock)",
  "Koźlak dubeltowy (doppelbock)",
  "Koźlak jesienny holenderski (herfstbok)",
  "Koźlak lodowy (eisbock)",
  "Koźlak pszeniczny (weizenbock)",
  "Koźlak wiosenny holenderski (lentebok)",
  "Kristallweizen",
  "Lager wiedeński",
  "Leichtbier",
  "Lichtenhainer",
  "Marcowe",
  "Mild ale",
  "Milk stout",
  "Nowofalowy pils",
  "Oak aged imperial stout",
  "Old ale",
  "Owocowe ale",
  "Pilzner niemiecki",
  "Piwo miodowe (braggot)",
  "Porter bałtycki",
  "Red IPA",
  "Rye wine",
  "Sahti",
  "Saison",
  "Schwarzbier",
  "Stout owsiany",
  "Szkockie ale",
  "Szkockie eksportowe ale",
  "Wędzone marcowe (rauchmaerzen)",
  "Wędzone pszeniczne (rauchweizen)",
  "Wędzony koźlak (rauchbock)",
  "Wędzony porter bałtycki",
  "Wędzony stout",
  "Wee heavy",
  "Weissbier",
  "Wheat IPA",
  "Wheatwine",
  "White IPA",
  "Winogronowe ale",
  "Witbier",
  "Żytnia IPA",
];
